<strong>Замена исключения проверкой условия</strong>

Проблема: Вы выбрасываете исключение там, где можно было бы обойтись простой проверкой условия.

Решение: Замените выбрасывание исключения проверкой этого условия.

Примеры: <a href="https://github.com/helenasilkina/refactoring/blob/master/Replace_Exception_with_Test.py">Replace_Exception_with_Test.py</a>, <a href="https://github.com/helenasilkina/refactoring/blob/master/Replace_Exception_with_Test.js">Replace_Exception_with_Test.js</a>

Причины рефакторинга:

1. Исключения должны использоваться для обработки внештатного поведения, связанного с неожиданной ошибкой. Они не должны служить заменой проверкам выполнения условий. Если исключения можно избежать, просто проверив какое-то условие перед выполнением действия, то стоит так и сделать. Исключения следует приберечь для настоящих ошибок.
2. Например, вы зашли на минное поле и там подорвались, вызвав исключение; исключение успешно обработалось и вас вынесло за пределы минного поля. Вместо этого можно бы было просто прочитать указатель перед минным полем и обойти его другой дорогой.

Достоинства: Простой условный оператор иногда может быть очевиднее блока обработки исключения.

Порядок рефакторинга:

1. Создайте условный оператор для граничного случая и поместите его перед try/catch блоком.
2. Переместите код из catch-секции внутрь этого условного оператора.
3. В catch-секции поставьте код выбрасывания обычного безымянного исключения и запустите все тесты.
4. Если никаких исключений не было выброшено во время тестов, избавьтесь от оператора try/catch.
